name: api

concurrency:
  group: ${{#mustacheCase}}github.workflow{{/mustacheCase}}-${{#mustacheCase}}github.ref{{/mustacheCase}}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "api/**"
      - ".github/workflows/api.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      dart_sdk: 3.4.3
      working_directory: api
      analyze_directories: "routes lib test"
      coverage_excludes: "**/*.g.dart"
      report_on: "routes,lib"
